#!/usr/bin/env python3
"""Generate every table and figure used by the venue-neutral manuscript.

The generator uses the standard library only.  It verifies the public evidence
before rendering Markdown tables and accessible SVG figures.  It never opens a
network, camera, microphone, or robot connection.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import verify_results  # noqa: E402


GENERATED = ROOT / "docs" / "paper" / "generated"
FIGURES = ROOT / "figures"
MANIFEST = GENERATED / "ARTIFACT_MANIFEST.json"
MANIFEST_SIDECAR = MANIFEST.with_suffix(MANIFEST.suffix + ".sha256")
MANUSCRIPT = ROOT / "docs" / "MANUSCRIPT.md"

SOURCE_FILES = (
    ROOT / "evidence" / "analysis" / "stage2a_policy_tournament_v1.json",
    ROOT / "evidence" / "manifests" / "stage3v_confirmation_result_v3_freeze.json",
    ROOT / "evidence" / "analysis" / "stage3v_trial_robustness_v1.json",
    ROOT / "evidence" / "manifests" / "stage3p_association_gated_cue_confirmation_result_v1_freeze.json",
    ROOT / "evidence" / "manifests" / "stage4a_supervised_motion_pilot_v3_diagnostic_freeze.json",
    ROOT / "evidence" / "analysis" / "av_synchrony_pilot_v2_public_summary_v1.json",
    ROOT / "evidence" / "manifests" / "av_synchrony_confirmation_protocol_v1.json",
)

PUBLICATION_FILES = (
    MANUSCRIPT,
    ROOT / "docs" / "AV_SYNCHRONY_CONFIRMATION_PROTOCOL.md",
    ROOT / "docs" / "HARDWARE_SOFTWARE_INVENTORY.md",
    ROOT / "docs" / "REPRODUCIBILITY.md",
    ROOT / "requirements-test.lock",
    ROOT / "evidence" / "manifests" / "reproducibility_environment_v1.json",
)


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _stage2_row(stage2: dict[str, Any], policy: str, split: str) -> dict[str, Any]:
    rows = [row for row in stage2["summary"] if row["policy"] == policy and row["split"] == split]
    if len(rows) != 1:
        raise ValueError(f"Expected one Stage 2A row for {policy}/{split}; got {len(rows)}")
    return rows[0]


def _inputs() -> dict[str, dict[str, Any]]:
    verify_results.verify_stage2a()
    verify_results.verify_stage3v()
    verify_results.verify_stage3p()
    verify_results.verify_stage4()
    verify_results.verify_avsync_v2()
    return {
        "stage2": load_json(SOURCE_FILES[0]),
        "stage3v": load_json(SOURCE_FILES[1]),
        "robustness": load_json(SOURCE_FILES[2]),
        "stage3p": load_json(SOURCE_FILES[3]),
        "stage4": load_json(SOURCE_FILES[4]),
        "avsync_v2": load_json(SOURCE_FILES[5]),
        "confirmation": load_json(SOURCE_FILES[6]),
    }


def render_stage_results(data: dict[str, dict[str, Any]]) -> str:
    selected = _stage2_row(data["stage2"], "3-hit safety consensus", "evaluation")
    v = data["stage3v"]["validated_state"]
    p = data["stage3p"]["validated_state"]
    m = data["stage4"]["validated_state"]
    a = data["avsync_v2"]
    lines = [
        "<!-- Generated by scripts/build_paper_artifacts.py; do not edit. -->",
        "",
        "| Stage | Unit and denominator | Frozen observation | Interpretation boundary |",
        "|---|---|---|---|",
        (
            "| 2A retrospective evaluation | 1 matching trial; 31 tracked rows; 37 tracked hard-negative rows | "
            f"3-hit policy confirmed {selected['matching_confirmed_rows']}/{selected['matching_tracking_rows']} matching and "
            f"{selected['hard_negative_confirmed_rows']}/{selected['hard_negative_tracking_rows']} hard-negative rows | "
            "Comparative internal evidence; complete matrix was inspected before the split |"
        ),
        (
            f"| 3V passive horizontal holdout | {v['accepted_trials']} accepted trials from {v['all_csv_attempts']} attempts | "
            f"{v['positive_trials_with_move']}/12 positives proposed; 0/6 accepted hard-negative trials proposed; "
            f"maximum target error {v['maximum_target_error_deg']:.3f}° | Small single-site holdout; no motion authority |"
        ),
        (
            f"| 3P passive cue boundary | {p['accepted_trials']} accepted trials from {p['all_csv_attempts']} attempts | "
            f"6/6 transitions cued; 0/{p['fail_closed_controls']} controls cued; {p['actuation_commands']} commands | "
            "Visual instruction only; not identity, consent, or authorization |"
        ),
        (
            f"| AV synchrony V2 pilot | {a['attempts']['canonical_quality_passing']} canonical trials from "
            f"{a['attempts']['total']} attempts | Development 4/4 positive and 0/4 negative; internal validation "
            "2/2 positive and 0/2 negative | Single-person instrument development; not confirmation |"
        ),
        (
            f"| 4A V3 physical pilot | {m['physical_motion_trials']} commanded trial | **FAIL**; motion "
            f"{m['robust_measured_motion_from_baseline_deg']:.3f}°, target error "
            f"{m['robust_target_to_requested_target_error_deg']:.3f}°, return error "
            f"{m['robust_return_to_baseline_error_deg']:.3f}° | No successful physical validation; thresholds unchanged |"
        ),
        "",
    ]
    return "\n".join(lines)


def render_attempt_accounting(data: dict[str, dict[str, Any]]) -> str:
    v = data["stage3v"]["validated_state"]
    p = data["stage3p"]["validated_state"]
    a = data["avsync_v2"]["attempts"]
    m = data["stage4"]["validated_state"]
    return "\n".join(
        [
            "<!-- Generated by scripts/build_paper_artifacts.py; do not edit. -->",
            "",
            "| Dataset | Accepted/analysed trials | Recorded attempts | Excluded/superseded | Primary unit |",
            "|---|---:|---:|---:|---|",
            "| Stage 2A passive matrix | 15 | Not reconstructable publicly | Not reconstructable publicly | Trial |",
            f"| Stage 3V horizontal holdout | {v['accepted_trials']} | {v['all_csv_attempts']} | {v['rejected_or_noncompliant_attempts']} | Trial |",
            f"| Stage 3P cue boundary | {p['accepted_trials']} | {p['all_csv_attempts']} | {p['superseded_attempts']} | Trial |",
            f"| AV synchrony V2 pilot | {a['canonical_quality_passing']} | {a['total']} | {a['quality_failed']} | Ten-second trial |",
            f"| Stage 4A V3 physical pilot | 0 passing | {m['physical_motion_trials']} | 1 failed, retained | Commanded physical trial |",
            "",
        ]
    )


THREATS = (
    (
        "Single operator and single robot",
        "Operator-specific speech, appearance, timing, setup skill, and one borrowed unit are confounded.",
        "Limit claims to a single-site research preview; use additional operators and robots before generalization.",
    ),
    (
        "Single-site room dependence",
        "Reflection, noise, microphone geometry, and illumination may drive the observed outcomes.",
        "The next protocol requires three newly bound rooms and reports results by room.",
    ),
    (
        "Correlated observations",
        "Telemetry rows within one trial are not independent samples.",
        "Use the trial as the inferential unit; row fractions remain descriptive.",
    ),
    (
        "Small trial counts",
        "Perfect observed fractions retain wide uncertainty (for example, Stage 3V 0/6 has a 39.0% Wilson upper endpoint).",
        "Report denominators and intervals; avoid population-safety language.",
    ),
    (
        "Researcher involvement",
        "The same research process designed, operated, repeated, audited, and analysed several stages.",
        "Retain every attempt, freeze rules before collection, and seek independent replication.",
    ),
    (
        "Retrospective Stage 2A split",
        "The full matrix had been inspected before development/evaluation labels were formalized.",
        "Call it comparative internal evidence, not a blind holdout.",
    ),
    (
        "V2 acquisition dependence",
        "Eleven failed attempts preceded twelve quality-passing trials; repeated captures may select easier performances.",
        "Apply only outcome-blind gates, retain failures, and prohibit pilot files in confirmation.",
    ),
    (
        "Microphone and device limitations",
        "The V2 signal is tied to one local audio path; the exact public device identity was not recorded, and headset placement can confound live speech versus playback.",
        "Bind one fixed microphone/camera configuration before confirmation; never wear a headset microphone during trials.",
    ),
    (
        "Failed physical validation",
        "The only commanded 3° trial missed its target and return tolerances.",
        "Preserve the failure; do not infer mechanical safety from offline IK or passive results.",
    ),
    (
        "No end-to-end test",
        "Compatibility, passive cueing, and the command boundary were tested separately.",
        "Do not claim speaker following, autonomous safety, or social attention behavior.",
    ),
    (
        "Incomplete hardware authorization and review",
        "Unit-specific failure recovery and permission for further hardware activity are outside the research evidence.",
        "Keep the successor non-executable; this paper makes no claim of external authorization and stores no correspondence.",
    ),
)


def render_threats() -> str:
    lines = [
        "<!-- Generated by scripts/build_paper_artifacts.py; do not edit. -->",
        "",
        "| Threat | Consequence | Treatment in this work |",
        "|---|---|---|",
    ]
    lines.extend(f"| {name} | {consequence} | {treatment} |" for name, consequence, treatment in THREATS)
    lines.append("")
    return "\n".join(lines)


def render_confirmation_design(data: dict[str, dict[str, Any]]) -> str:
    manifest = data["confirmation"]
    counts: dict[str, int] = {}
    roles: dict[str, str] = {}
    descriptions: dict[str, str] = {}
    for condition in manifest["conditions"]:
        condition_id = condition["id"]
        counts[condition_id] = sum(
            item["condition_id"] == condition_id for item in manifest["canonical_trials"]
        )
        roles[condition_id] = condition["role"]
        descriptions[condition_id] = condition["description"]
    lines = [
        "<!-- Generated by scripts/build_paper_artifacts.py; do not edit. -->",
        "",
        "| Frozen condition | Role | Trials | Purpose |",
        "|---|---|---:|---|",
    ]
    for condition in manifest["conditions"]:
        condition_id = condition["id"]
        lines.append(
            f"| `{condition_id}` | {roles[condition_id].replace('_', ' ')} | {counts[condition_id]} | {descriptions[condition_id]} |"
        )
    lines.extend(
        [
            "",
            f"Protocol fingerprint: `{manifest['fingerprint']}`. The 54 trials comprise 18 matching positives and 36 hard negatives across three rooms and three visible-person headings.",
            "",
        ]
    )
    return "\n".join(lines)


def render_architecture_svg() -> str:
    boxes = [
        (60, 210, 280, 300, "Local numeric evidence", ["DoA + speech state", "Face geometry", "Freshness + health"]),
        (410, 210, 280, 300, "Compatibility gate", ["PROPOSE candidate", "or ABSTAIN / HOLD", "No identity claim"]),
        (760, 210, 280, 300, "Human boundary", ["Passive cue", "Separate typed arm", "No implied consent"]),
        (1110, 210, 330, 300, "Mechanical boundary", ["Fresh preflight", "Bounded one-shot scope", "Target and return split"]),
    ]
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1500" height="760" viewBox="0 0 1500 760" role="img" aria-labelledby="title desc">',
        '<title id="title">Abstention-first permission architecture</title>',
        '<desc id="desc">Four separately inspectable boundaries lead from local numeric evidence to a bounded mechanical decision. Missing or conflicting evidence leads to abstention. The stages are not validated end to end.</desc>',
        '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto"><path d="M0 0 L10 5 L0 10 Z" fill="#167d75"/></marker></defs>',
        '<rect width="1500" height="760" fill="#f7fafc"/>',
        '<text x="60" y="80" font-family="Segoe UI,Arial,sans-serif" font-size="42" font-weight="700" fill="#102a43">Movement as a permission decision</text>',
        '<text x="60" y="125" font-family="Segoe UI,Arial,sans-serif" font-size="23" fill="#486581">Separately tested research boundaries; no end-to-end or certified-safety claim</text>',
    ]
    for index, (x, y, width, height, title, lines) in enumerate(boxes):
        fill = "#e6fffa" if index == 3 else "#ffffff"
        stroke = "#167d75" if index == 3 else "#9fb3c8"
        parts.append(f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="22" fill="{fill}" stroke="{stroke}" stroke-width="3"/>')
        parts.append(f'<text x="{x + 25}" y="{y + 58}" font-family="Segoe UI,Arial,sans-serif" font-size="27" font-weight="700" fill="#102a43">{html.escape(title)}</text>')
        for line_index, line in enumerate(lines):
            parts.append(f'<text x="{x + 25}" y="{y + 120 + line_index * 48}" font-family="Segoe UI,Arial,sans-serif" font-size="21" fill="#334e68">{html.escape(line)}</text>')
        if index < len(boxes) - 1:
            x1 = x + width + 12
            x2 = boxes[index + 1][0] - 12
            parts.append(f'<line x1="{x1}" y1="360" x2="{x2}" y2="360" stroke="#167d75" stroke-width="5" marker-end="url(#arrow)"/>')
    parts.extend(
        [
            '<rect x="60" y="565" width="1380" height="115" rx="18" fill="#102a43"/>',
            '<text x="750" y="615" text-anchor="middle" font-family="Segoe UI,Arial,sans-serif" font-size="26" font-weight="700" fill="#ffffff">Any missing, stale, ambiguous, conflicting, or unauthorized state → ABSTAIN / HOLD</text>',
            '<text x="750" y="655" text-anchor="middle" font-family="Segoe UI,Arial,sans-serif" font-size="21" fill="#d9e2ec">After a target, return requires a fresh state and separate authorization; failure does not trigger automatic motion.</text>',
            '</svg>',
            '',
        ]
    )
    return "\n".join(parts)


def render_frontier_svg(data: dict[str, dict[str, Any]]) -> str:
    stage2 = data["stage2"]
    policies = [
        ("Recorded Stage 2A", "Recorded", "#d64545"),
        ("Current speech only", "Speech-now", "#2f6fed"),
        ("Short hold 250 ms + disagreement reset", "250 ms hold", "#f59f00"),
        ("2-hit consensus + reset", "2-hit", "#7950b3"),
        ("3-hit safety consensus", "3-hit", "#0f9d8a"),
    ]
    panels = (("development", 95, "Development repetitions 1–2"), ("evaluation", 795, "Retrospective evaluation repetition 3"))
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1500" height="720" viewBox="0 0 1500 720" role="img" aria-labelledby="title desc">',
        '<title id="title">Stage 2A passive safety-coverage frontier</title>',
        '<desc id="desc">Development and retrospective evaluation plots compare tracked matching coverage against tracked hard-negative false confirmation. Upper left is preferable. The development-selected three-hit policy is marked with a star.</desc>',
        '<rect width="1500" height="720" fill="#ffffff"/>',
        '<text x="70" y="65" font-family="Segoe UI,Arial,sans-serif" font-size="39" font-weight="700" fill="#102a43">Passive acoustic–visual policy frontier</text>',
        '<text x="70" y="105" font-family="Segoe UI,Arial,sans-serif" font-size="21" fill="#486581">Upper-left is preferable. Coverage and false-confirmation percentages use correlated tracked rows and are descriptive.</text>',
    ]
    for split, left, title in panels:
        top, width, height = 205, 590, 360
        parts.append(f'<text x="{left}" y="165" font-family="Segoe UI,Arial,sans-serif" font-size="27" font-weight="700" fill="#102a43">{title}</text>')
        for tick in range(0, 101, 20):
            y = top + height - height * tick / 100
            parts.append(f'<line x1="{left}" y1="{y:.1f}" x2="{left + width}" y2="{y:.1f}" stroke="#d9e2ec" stroke-width="1"/>')
            parts.append(f'<text x="{left - 12}" y="{y + 6:.1f}" text-anchor="end" font-family="Segoe UI,Arial,sans-serif" font-size="17" fill="#627d98">{tick}</text>')
        for tick in (0, 10, 20, 30):
            x = left + width * tick / 32
            parts.append(f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + height}" stroke="#d9e2ec" stroke-width="1"/>')
            parts.append(f'<text x="{x:.1f}" y="{top + height + 28}" text-anchor="middle" font-family="Segoe UI,Arial,sans-serif" font-size="17" fill="#627d98">{tick}</text>')
        parts.append(f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top + height}" stroke="#829ab1" stroke-width="2"/>')
        parts.append(f'<line x1="{left}" y1="{top + height}" x2="{left + width}" y2="{top + height}" stroke="#829ab1" stroke-width="2"/>')
        parts.append(f'<text x="{left}" y="{top - 15}" font-family="Segoe UI,Arial,sans-serif" font-size="18" fill="#486581">Tracked matching coverage (%)</text>')
        parts.append(f'<text x="{left + width / 2}" y="{top + height + 63}" text-anchor="middle" font-family="Segoe UI,Arial,sans-serif" font-size="18" fill="#486581">Tracked hard-negative false confirmation (%)</text>')
        for policy, label, colour in policies:
            row = _stage2_row(stage2, policy, split)
            x_value = row["hard_negative_false_per_tracking_pct"]
            y_value = row["matching_tracked_coverage_pct"]
            x = left + width * x_value / 32
            y = top + height - height * y_value / 100
            if policy == "3-hit safety consensus":
                parts.append(f'<text x="{x:.1f}" y="{y + 9:.1f}" text-anchor="middle" font-family="Segoe UI Symbol,Arial,sans-serif" font-size="31" fill="{colour}">★</text>')
            else:
                parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="8" fill="{colour}"/>')
            dx = 12 if x_value < 24 else -12
            anchor = "start" if dx > 0 else "end"
            parts.append(f'<text x="{x + dx:.1f}" y="{y - 10:.1f}" text-anchor="{anchor}" font-family="Segoe UI,Arial,sans-serif" font-size="17" fill="#243b53">{label}</text>')
    parts.extend(
        [
            '<text x="70" y="680" font-family="Segoe UI,Arial,sans-serif" font-size="18" fill="#486581">The evaluation repetition was frozen only after the full matrix had been inspected; it is not a pristine blind holdout.</text>',
            '</svg>',
            '',
        ]
    )
    return "\n".join(parts)


def rendered_outputs(data: dict[str, dict[str, Any]]) -> dict[Path, bytes]:
    return {
        GENERATED / "TABLE_1_STAGE_RESULTS.md": render_stage_results(data).encode("utf-8"),
        GENERATED / "TABLE_2_ATTEMPT_ACCOUNTING.md": render_attempt_accounting(data).encode("utf-8"),
        GENERATED / "TABLE_3_THREATS_TO_VALIDITY.md": render_threats().encode("utf-8"),
        GENERATED / "TABLE_4_CONFIRMATION_DESIGN.md": render_confirmation_design(data).encode("utf-8"),
        FIGURES / "architecture.svg": render_architecture_svg().encode("utf-8"),
        FIGURES / "safety-coverage-frontier.svg": render_frontier_svg(data).encode("utf-8"),
    }


def rendered_manifest(outputs: dict[Path, bytes]) -> bytes:
    payload = {
        "schema": "reachy-paper-artifact-manifest-v1",
        "generator": "scripts/build_paper_artifacts.py",
        "sources": [
            {"path": path.relative_to(ROOT).as_posix(), "sha256": sha256_file(path)}
            for path in SOURCE_FILES
        ],
        "outputs": [
            {
                "path": path.relative_to(ROOT).as_posix(),
                "bytes": len(content),
                "sha256": sha256_bytes(content),
            }
            for path, content in sorted(outputs.items(), key=lambda item: item[0].as_posix())
        ],
        "publication_files": [
            {"path": path.relative_to(ROOT).as_posix(), "sha256": sha256_file(path)}
            for path in PUBLICATION_FILES
        ],
        "boundaries": {
            "network_connections": 0,
            "robot_connections": 0,
            "media_capture": 0,
            "figures_are_svg": True,
        },
    }
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        data = _inputs()
        outputs = rendered_outputs(data)
        manuscript = MANUSCRIPT.read_text(encoding="utf-8")
        missing_tables = [
            path.name
            for path, content in outputs.items()
            if path.suffix == ".md" and content.decode("utf-8").strip() not in manuscript
        ]
        if missing_tables:
            print(
                "FAIL: manuscript does not contain the generated version of: "
                + ", ".join(missing_tables),
                file=sys.stderr,
            )
            return 1
        manifest = rendered_manifest(outputs)
        sidecar = f"{sha256_bytes(manifest)}  {MANIFEST.name}\n".encode("utf-8")
        expected = {**outputs, MANIFEST: manifest, MANIFEST_SIDECAR: sidecar}
        if args.write:
            for path, content in expected.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
                print(f"WROTE: {path.relative_to(ROOT)}")
            return 0
        stale = [
            path.relative_to(ROOT).as_posix()
            for path, content in expected.items()
            if not path.is_file() or path.read_bytes() != content
        ]
        if stale:
            print("FAIL: stale or missing paper artifacts:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"PASS: {len(outputs)} manuscript tables/figures match verified evidence.")
        print("PASS: all generated tables are embedded verbatim in docs/MANUSCRIPT.md.")
        print(f"PASS: paper artifact manifest binds {len(SOURCE_FILES)} source artifacts.")
        return 0
    except (AssertionError, KeyError, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
